import type { DentalCase } from '@/lib/geometry';
import type { Pose, Transforms, Vec3 } from '@/lib/model';
import type { Landmark } from '@/lib/appliances';
import type { WorkflowViewState } from '@/lib/workflow-appliances';
import type { AnatomyViewState } from '@/lib/teaching-anatomy';
import type { MechanicsExperiment } from '@/lib/mechanics/types';
import type { PointedReference } from '@/lib/mechanics-commands';
import type { ToothStudyView } from '@/lib/tooth-study/types';

export type ViewerToothStudy = { tooth: string; view: ToothStudyView; revision: number };
export type ViewName = 'perspective' | 'occlusal' | 'front' | 'right' | 'left';
export type ArchView = 'both' | 'upper' | 'lower';
export type ViewerCamera = {
  position: Vec3;
  target: Vec3;
  up: Vec3;
  view: ViewName;
  far: number;
  maxDistance: number;
};
export type ViewerHandle = {
  setView: (view: ViewName) => void;
  fit: () => void;
  focus: () => void;
  snapshot: () => void;
  getCamera: () => ViewerCamera | null;
  restoreCamera: (camera: ViewerCamera) => void;
  whenRendered: (signal: AbortSignal) => Promise<void>;
};
export type ViewerProps = {
  toothStudy?: ViewerToothStudy | null;
  model: DentalCase;
  transforms: Transforms;
  selected: string;
  selectedIds: string[];
  onSelect: (id: string, additive: boolean) => void;
  ghost: boolean;
  gums: boolean;
  labels: boolean;
  grid: boolean;
  arch: ArchView;
  braces: boolean;
  roots: boolean;
  bracketStyle: 'metal' | 'ceramic';
  ligatureColor: string;
  opening: number;
  measureMode: boolean;
  landmarks: Landmark[];
  onLandmark: (landmark: Landmark) => void;
  intersections: string[];
  attachments: boolean;
  tool: 'orbit' | 'translate' | 'rotate';
  onPosePreview: (id: string, pose: Pose) => void;
  onPoseCommit: (id: string, pose: Pose) => void;
  workflow?: WorkflowViewState;
  paused?: boolean;
  anatomy?: AnatomyViewState;
  ghostTransforms?: Transforms;
  lockedIds?: string[];
  traceFrom?: Transforms;
  archCurve?: Vec3[];
  removableRetainer?: boolean;
  isolateSelection?: boolean;
  mechanics?: MechanicsExperiment | null;
  mechanicsForces?: boolean;
  mechanicsRevealed?: boolean;
  pointed?: PointedReference | null;
  pointing?: boolean;
  onPoint?: (point: PointedReference | null) => void;
  onReferenceInteraction?: () => void;
};
